insert into employee (id, first_name, last_name, email, version) values (1, 'Belle', 'Kamena', 'bkamena0@vkontakte.ru', 0) on conflict (id) do nothing;
insert into employee (id, first_name, last_name, email, version) values (2, 'Vito', 'Maystone', 'vmaystone1@reuters.com', 0) on conflict (id) do nothing;
insert into employee (id, first_name, last_name, email, version) values (3, 'Kristen', 'Stollberger', 'kstollberger2@aboutads.info', 0) on conflict (id) do nothing;
insert into employee (id, first_name, last_name, email, version) values (4, 'Boot', 'O''Connell', 'boconnell3@vk.com', 0) on conflict (id) do nothing;
insert into employee (id, first_name, last_name, email, version) values (5, 'Carmencita', 'Jacomb', 'cjacomb4@hc360.com', 0) on conflict (id) do nothing;
insert into employee (id, first_name, last_name, email, version) values (6, 'Cilka', 'Trustrie', 'ctrustrie5@hhs.gov', 0) on conflict (id) do nothing;
insert into employee (id, first_name, last_name, email, version) values (7, 'Hasty', 'Beers', 'hbeers6@phoca.cz', 0) on conflict (id) do nothing;
insert into employee (id, first_name, last_name, email, version) values (8, 'Neddy', 'Birth', 'nbirth7@e-recht24.de', 0) on conflict (id) do nothing;
insert into employee (id, first_name, last_name, email, version) values (9, 'Kacie', 'Uden', 'kuden8@example.com', 0) on conflict (id) do nothing;
insert into employee (id, first_name, last_name, email, version) values (10, 'Merry', 'Herreros', 'mherreros9@jigsy.com', 0) on conflict (id) do nothing;
insert into employee (id, first_name, last_name, email, version) values (11, 'Les', 'Conibeer', 'lconibeera@purevolume.com', 0) on conflict (id) do nothing;
insert into employee (id, first_name, last_name, email, version) values (12, 'Trisha', 'Kainz', 'tkainzb@google.co.uk', 0) on conflict (id) do nothing;
insert into employee (id, first_name, last_name, email, version) values (13, 'Felice', 'Rea', 'freac@si.edu', 0) on conflict (id) do nothing;
insert into employee (id, first_name, last_name, email, version) values (14, 'Joe', 'Adamowicz', 'jadamowiczd@t.co', 0) on conflict (id) do nothing;
insert into employee (id, first_name, last_name, email, version) values (15, 'Jacquelynn', 'Erangey', 'jerangeye@bloomberg.com', 0) on conflict (id) do nothing;
insert into employee (id, first_name, last_name, email, version) values (16, 'Sergeant', 'Jillions', 'sjillionsf@bloglines.com', 0) on conflict (id) do nothing;
insert into employee (id, first_name, last_name, email, version) values (17, 'Teodoro', 'Rabjohn', 'trabjohng@google.de', 0) on conflict (id) do nothing;
insert into employee (id, first_name, last_name, email, version) values (18, 'Bud', 'MacAllen', 'bmacallenh@businesswire.com', 0) on conflict (id) do nothing;
insert into employee (id, first_name, last_name, email, version) values (19, 'Quintana', 'St. John', 'qstjohni@weather.com', 0) on conflict (id) do nothing;
insert into employee (id, first_name, last_name, email, version) values (20, 'Chicky', 'Ioselevich', 'cioselevichj@imgur.com', 0) on conflict (id) do nothing;
insert into employee (id, first_name, last_name, email, version) values (21, 'Dollie', 'Bartlomiej', 'dbartlomiejk@census.gov', 0) on conflict (id) do nothing;
insert into employee (id, first_name, last_name, email, version) values (22, 'Ozzy', 'Aldersey', 'oalderseyl@tinypic.com', 0) on conflict (id) do nothing;
insert into employee (id, first_name, last_name, email, version) values (23, 'Minnaminnie', 'Buesden', 'mbuesdenm@hhs.gov', 0) on conflict (id) do nothing;
insert into employee (id, first_name, last_name, email, version) values (24, 'Windham', 'Full', 'wfulln@bloomberg.com', 0) on conflict (id) do nothing;
insert into employee (id, first_name, last_name, email, version) values (25, 'Gracia', 'Kildea', 'gkildeao@mac.com', 0) on conflict (id) do nothing;
insert into employee (id, first_name, last_name, email, version) values (26, 'Alyosha', 'Franssen', 'afranssenp@google.ca', 0) on conflict (id) do nothing;
insert into employee (id, first_name, last_name, email, version) values (27, 'Cairistiona', 'Smee', 'csmeeq@census.gov', 0) on conflict (id) do nothing;
insert into employee (id, first_name, last_name, email, version) values (28, 'Elfreda', 'Pratley', 'epratleyr@columbia.edu', 0) on conflict (id) do nothing;
insert into employee (id, first_name, last_name, email, version) values (29, 'Mohammed', 'Shawdforth', 'mshawdforths@comcast.net', 0) on conflict (id) do nothing;
insert into employee (id, first_name, last_name, email, version) values (30, 'Kerrie', 'Fodden', 'kfoddent@quantcast.com', 0) on conflict (id) do nothing;
insert into employee (id, first_name, last_name, email, version) values (31, 'Faber', 'Bourthoumieux', 'fbourthoumieuxu@163.com', 0) on conflict (id) do nothing;
insert into employee (id, first_name, last_name, email, version) values (32, 'Myrah', 'Dresse', 'mdressev@yelp.com', 0) on conflict (id) do nothing;
insert into employee (id, first_name, last_name, email, version) values (33, 'Sebastiano', 'Low', 'sloww@europa.eu', 0) on conflict (id) do nothing;
insert into employee (id, first_name, last_name, email, version) values (34, 'Thorin', 'Demonge', 'tdemongex@ca.gov', 0) on conflict (id) do nothing;
insert into employee (id, first_name, last_name, email, version) values (35, 'Noach', 'Rentoul', 'nrentouly@facebook.com', 0) on conflict (id) do nothing;
insert into employee (id, first_name, last_name, email, version) values (36, 'Kathrine', 'Du Hamel', 'kduhamelz@mayoclinic.com', 0) on conflict (id) do nothing;
insert into employee (id, first_name, last_name, email, version) values (37, 'Barnabe', 'Hodgets', 'bhodgets10@histats.com', 0) on conflict (id) do nothing;
insert into employee (id, first_name, last_name, email, version) values (38, 'Moshe', 'Grinov', 'mgrinov11@cocolog-nifty.com', 0) on conflict (id) do nothing;
insert into employee (id, first_name, last_name, email, version) values (39, 'Aloin', 'Awcock', 'aawcock12@dmoz.org', 0) on conflict (id) do nothing;
insert into employee (id, first_name, last_name, email, version) values (40, 'Christabella', 'Athy', 'cathy13@examiner.com', 0) on conflict (id) do nothing;
insert into employee (id, first_name, last_name, email, version) values (41, 'Rees', 'Castanone', 'rcastanone14@webnode.com', 0) on conflict (id) do nothing;
insert into employee (id, first_name, last_name, email, version) values (42, 'Steve', 'Goldwater', 'sgoldwater15@oracle.com', 0) on conflict (id) do nothing;
insert into employee (id, first_name, last_name, email, version) values (43, 'Pavia', 'Sawfoot', 'psawfoot16@goo.gl', 0) on conflict (id) do nothing;
insert into employee (id, first_name, last_name, email, version) values (44, 'Allayne', 'Kisar', 'akisar17@zdnet.com', 0) on conflict (id) do nothing;
insert into employee (id, first_name, last_name, email, version) values (45, 'Vikki', 'Ezzell', 'vezzell18@goo.gl', 0) on conflict (id) do nothing;
insert into employee (id, first_name, last_name, email, version) values (46, 'Roma', 'Verdie', 'rverdie19@hatena.ne.jp', 0) on conflict (id) do nothing;
insert into employee (id, first_name, last_name, email, version) values (47, 'Tammy', 'Wheldon', 'twheldon1a@indiegogo.com', 0) on conflict (id) do nothing;
insert into employee (id, first_name, last_name, email, version) values (48, 'Bastien', 'Blanche', 'bblanche1b@google.com.br', 0) on conflict (id) do nothing;
insert into employee (id, first_name, last_name, email, version) values (49, 'Callean', 'Elmer', 'celmer1c@technorati.com', 0) on conflict (id) do nothing;
insert into employee (id, first_name, last_name, email, version) values (50, 'Christiana', 'Abernethy', 'cabernethy1d@indiatimes.com', 0) on conflict (id) do nothing;

--Set the primary key sequence to the current maximum id to sync it and to avoid duplicate key value error
select setval('employee_id_seq', max(id)) from employee;
